from django.urls import path

from archaea_database.views import genomes_views, proteins_views, tRNAs_views, crisprcas_views, anti_cripsr_views, \
    secondary_metabolites_views, signal_peptide_views, virulence_factor_views, antibiotic_resistance_views, \
    transmembrane_helices_views

urlpatterns = [
    path('genomes', genomes_views.ArchaeaGenomesView.as_view()),
    path('genomes_unmag', genomes_views.UnMAGArchaeaGenomesView.as_view()),
    path('genomes_filter_options', genomes_views.ArchaeaGenomesFilterOptionsView.as_view()),
    path('genomes_filter_options_unmag', genomes_views.UnMAGArchaeaGenomesFilterOptionsView.as_view()),
    path('genome_single_download', genomes_views.ArchaeaGenomesSingleDownloadView.as_view()),
    path('genome_single_download_unmag', genomes_views.UnMAGArchaeaGenomesSingleDownloadView.as_view()),
    path('genome_batch_download', genomes_views.ArchaeaGenomesBatchDownloadView.as_view()),
    path('genome_batch_download_unmag', genomes_views.UnMAGArchaeaGenomesBatchDownloadView.as_view()),
    path('proteins', proteins_views.ArchaeaProteinsView.as_view()),
    path('proteins_unmag', proteins_views.UnMAGArchaeaProteinsView.as_view()),
    path('proteins_filter_options', proteins_views.ArchaeaProteinsFilterOptionsView.as_view()),
    path('proteins_filter_options_unmag', proteins_views.UnMAGArchaeaProteinsFilterOptionsView.as_view()),
    path('protein_single_download', proteins_views.ArchaeaProteinsSingleDownloadView.as_view()),
    path('protein_single_download_unmag', proteins_views.UnMAGArchaeaProteinsSingleDownloadView.as_view()),
    path('protein_batch_download', proteins_views.ArchaeaProteinsBatchDownloadView.as_view()),
    path('protein_batch_download_unmag', proteins_views.UnMAGArchaeaProteinsBatchDownloadView.as_view()),
    path('tRNAs', tRNAs_views.ArchaeaTRNAsView.as_view()),
    path('tRNAs_unmag', tRNAs_views.UnMAGArchaeaTRNAsView.as_view()),
    path('tRNAs_filter_options', tRNAs_views.ArchaeaTRNAFilterOptionsView.as_view()),
    path('tRNAs_filter_options_unmag', tRNAs_views.UnMAGArchaeaTRNAFilterOptionsView.as_view()),
    path('tRNA_single_download', tRNAs_views.ArchaeaTRNASingleDownloadView.as_view()),
    path('tRNA_single_download_unmag', tRNAs_views.UnMAGArchaeaTRNASingleDownloadView.as_view()),
    path('tRNA_batch_download', tRNAs_views.ArchaeaTRNABatchDownloadView.as_view()),
    path('tRNA_batch_download_unmag', tRNAs_views.UnMAGArchaeaTRNABatchDownloadView.as_view()),
    path('CRISPR_Cas_systems', crisprcas_views.ArchaeaCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_unmag', crisprcas_views.UnMAGArchaeaCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_filter_options', crisprcas_views.ArchaeaCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_systems_filter_options_unmag',
         crisprcas_views.UnMAGArchaeaCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_system_single_download', crisprcas_views.ArchaeaCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_single_download_unmag',
         crisprcas_views.UnMAGArchaeaCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download', crisprcas_views.ArchaeaCRISPRCasSystemsBatchDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download_unmag',
         crisprcas_views.UnMAGArchaeaCRISPRCasSystemsBatchDownloadView.as_view()),
    path('anti_crispr_annotations', anti_cripsr_views.ArchaeaAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_unmag', anti_cripsr_views.UnMAGArchaeaAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_filter_options',
         anti_cripsr_views.ArchaeaAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotations_filter_options_unmag',
         anti_cripsr_views.UnMAGArchaeaAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotation_single_download',
         anti_cripsr_views.ArchaeaAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_single_download_unmag',
         anti_cripsr_views.UnMAGArchaeaAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download',
         anti_cripsr_views.ArchaeaAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download_unmag',
         anti_cripsr_views.UnMAGArchaeaAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('secondary_metabolites', secondary_metabolites_views.ArchaeaSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_unmag', secondary_metabolites_views.UnMAGArchaeaSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_filter_options',
         secondary_metabolites_views.ArchaeaSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolites_filter_options_unmag',
         secondary_metabolites_views.UnMAGArchaeaSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolite_single_download',
         secondary_metabolites_views.ArchaeaSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_single_download_unmag',
         secondary_metabolites_views.UnMAGArchaeaSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_batch_download',
         secondary_metabolites_views.ArchaeaSecondaryMetabolitesBatchDownloadView.as_view()),
    path('secondary_metabolite_batch_download_unmag',
         secondary_metabolites_views.UnMAGArchaeaSecondaryMetabolitesBatchDownloadView.as_view()),
    path('signal_peptides', signal_peptide_views.ArchaeaSignalPeptidesView.as_view()),
    path('signal_peptides_unmag', signal_peptide_views.UnMAGArchaeaSignalPeptidesView.as_view()),
    path('signal_peptides_filter_options', signal_peptide_views.ArchaeaSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptides_filter_options_unmag',
         signal_peptide_views.UnMAGArchaeaSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptide_single_download', signal_peptide_views.ArchaeaSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_single_download_unmag',
         signal_peptide_views.UnMAGArchaeaSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_batch_download', signal_peptide_views.ArchaeaSignalPeptidesBatchDownloadView.as_view()),
    path('signal_peptide_batch_download_unmag',
         signal_peptide_views.UnMAGArchaeaSignalPeptidesBatchDownloadView.as_view()),
    path('virulence_factors', virulence_factor_views.ArchaeaVirulenceFactorsView.as_view()),
    path('virulence_factors_unmag', virulence_factor_views.UnMAGArchaeaVirulenceFactorsView.as_view()),
    path('virulence_factors_filter_options', virulence_factor_views.ArchaeaVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factors_filter_options_unmag',
         virulence_factor_views.UnMAGArchaeaVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factor_single_download', virulence_factor_views.ArchaeaVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_single_download_unmag',
         virulence_factor_views.UnMAGArchaeaVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_batch_download', virulence_factor_views.ArchaeaVirulenceFactorsBatchDownloadView.as_view()),
    path('virulence_factor_batch_download_unmag',
         virulence_factor_views.UnMAGArchaeaVirulenceFactorsBatchDownloadView.as_view()),
    path('antibiotic_resistances', antibiotic_resistance_views.ArchaeaAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_unmag', antibiotic_resistance_views.UnMAGArchaeaAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_filter_options',
         antibiotic_resistance_views.ArchaeaAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistances_filter_options_unmag',
         antibiotic_resistance_views.UnMAGArchaeaAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistance_single_download',
         antibiotic_resistance_views.ArchaeaAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_single_download_unmag',
         antibiotic_resistance_views.UnMAGArchaeaAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_batch_download',
         antibiotic_resistance_views.ArchaeaAntibioticResistancesBatchDownloadView.as_view()),
    path('antibiotic_resistance_batch_download_unmag',
         antibiotic_resistance_views.UnMAGArchaeaAntibioticResistancesBatchDownloadView.as_view()),
    path('transmembrane_helices', transmembrane_helices_views.ArchaeaTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_unmag', transmembrane_helices_views.UnMAGArchaeaTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_filter_options',
         transmembrane_helices_views.ArchaeaTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helices_filter_options_unmag',
         transmembrane_helices_views.UnMAGArchaeaTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helice_single_download',
         transmembrane_helices_views.ArchaeaTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_single_download_unmag',
         transmembrane_helices_views.UnMAGArchaeaTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_batch_download',
         transmembrane_helices_views.ArchaeaTransmembraneHelicesBatchDownloadView.as_view()),
    path('transmembrane_helice_batch_download_unmag',
         transmembrane_helices_views.UnMAGArchaeaTransmembraneHelicesBatchDownloadView.as_view()),
    path('genome_detail', genomes_views.ArchaeaGenomeDetailView.as_view()),
    path('genome_detail_unmag', genomes_views.UnArchaeaGenomeDetailView.as_view()),
    path('genome_detail_proteins', genomes_views.ArchaeaGenomeProteinsView.as_view()),
    path('genome_detail_proteins_unmag', genomes_views.UnArchaeaGenomeProteinsView.as_view()),
    path('genome_fasta', genomes_views.ArchaeaGenomeFASTAView.as_view()),
    path('genome_fasta_unmag', genomes_views.UnMAGArchaeaGenomeFASTAView.as_view())
]
