# Generated by Django 4.2 on 2025-05-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MAGViruses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id_GCA",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "viruses_id_GCF",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("organism_name", models.CharField(blank=True, max_length=255)),
                ("taxonomic_id", models.PositiveIntegerField(blank=True, null=True)),
                ("species", models.CharField(blank=True, max_length=255)),
                (
                    "total_sequence_length",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("gc_content", models.FloatField(blank=True, null=True)),
                ("assembly_level", models.CharField(blank=True, max_length=100)),
                (
                    "total_chromosomes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("contig_n50", models.BigIntegerField(blank=True, null=True)),
                ("scaffold_n50", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Genome",
                "verbose_name_plural": "MAG Viruses Genomes",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesAntibioticResistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("product", models.TextField(blank=True)),
                ("arg_database", models.CharField(blank=True, max_length=255)),
                ("cutoff", models.CharField(blank=True, max_length=255)),
                ("hsp_identifier", models.CharField(blank=True, max_length=255)),
                ("best_hit_aro", models.CharField(blank=True, max_length=255)),
                ("best_identities", models.FloatField(blank=True, null=True)),
                ("aro", models.IntegerField(blank=True, null=True)),
                ("drug_class", models.TextField(blank=True)),
                ("resistance_mechanism", models.CharField(blank=True, max_length=255)),
                ("amr_gene_family", models.CharField(blank=True, max_length=255)),
                ("antibiotic", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
                ("snps_in_best_hit_aro", models.TextField(blank=True)),
                ("other_snps", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Antibiotic Resistance Gene",
                "verbose_name_plural": "MAG Viruses Antibiotic Resistance Genes",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesAntiCRISPRAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("classification", models.CharField(blank=True, max_length=255)),
                ("aa_length", models.PositiveIntegerField(blank=True, null=True)),
                ("acr_aca", models.TextField(blank=True)),
                ("mge_metadata", models.TextField(blank=True)),
                ("acr_hit_pident", models.CharField(blank=True, max_length=255)),
                ("sequence", models.TextField(blank=True)),
                ("self_target_within_5kb", models.TextField(blank=True)),
                ("self_target_outside_5kb", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Anti-CRISPR Annotation",
                "verbose_name_plural": "MAG Viruses Anti-CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesCRISPRCas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("cas_id", models.CharField(blank=True, max_length=100)),
                ("cas_start", models.BigIntegerField(blank=True, null=True)),
                ("cas_end", models.BigIntegerField(blank=True, null=True)),
                ("cas_subtype", models.CharField(blank=True, max_length=255)),
                ("consensus_prediction", models.CharField(blank=True, max_length=255)),
                ("cas_genes", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "verbose_name": "MAG Viruses CRISPRC CAS Annotation",
                "verbose_name_plural": "MAG Viruses CRISPRC CAS Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("orf_prediction_source", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("phase", models.PositiveIntegerField(blank=True, null=True)),
                ("product", models.TextField(blank=True)),
                (
                    "function_prediction_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cog_category", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("preferred_name", models.CharField(blank=True, max_length=255)),
                ("gos", models.TextField(blank=True)),
                ("ec", models.CharField(blank=True, max_length=255)),
                ("kegg_ko", models.TextField(blank=True)),
                ("kegg_pathway", models.TextField(blank=True)),
                ("kegg_module", models.TextField(blank=True)),
                ("kegg_reaction", models.TextField(blank=True)),
                ("kegg_rclass", models.TextField(blank=True)),
                ("brite", models.TextField(blank=True)),
                ("kegg_tc", models.TextField(blank=True)),
                ("cazy", models.TextField(blank=True)),
                ("bigg_reaction", models.TextField(blank=True)),
                ("pfams", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Protein Annotation",
                "verbose_name_plural": "MAG Viruses Protein Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "organism_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxonomy_id", models.PositiveIntegerField(blank=True, null=True)),
                ("acellular_root", models.CharField(blank=True, max_length=255)),
                ("realm", models.CharField(blank=True, max_length=255)),
                ("kingdom", models.CharField(blank=True, max_length=255)),
                ("phylum", models.CharField(blank=True, max_length=255)),
                ("class_name", models.CharField(blank=True, max_length=255)),
                ("order", models.CharField(blank=True, max_length=255)),
                ("family", models.CharField(blank=True, max_length=255)),
                ("genus", models.CharField(blank=True, max_length=255)),
                ("species", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "MAG Viruses Taxonomy",
                "verbose_name_plural": "MAG Viruses Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesTransmembraneHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("protein_id", models.CharField(blank=True, max_length=100)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "predicted_tmh_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("expected_aas_in_tmh", models.FloatField(blank=True, null=True)),
                ("expected_first_60_aas", models.FloatField(blank=True, null=True)),
                ("total_prob_n_in", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Transmembrane Helix",
                "verbose_name_plural": "MAG Viruses Transmembrane Helices",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesTRNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "trna_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("trna_type", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(0, "forward"), (1, "reverse")], default=0
                    ),
                ),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Viruses tRNA Annotation",
                "verbose_name_plural": "MAG Viruses tRNA Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesVirulenceFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vf_database", models.CharField(blank=True, max_length=255)),
                ("vfseq_id", models.CharField(blank=True, max_length=255)),
                ("identity", models.FloatField(blank=True, null=True)),
                ("e_value", models.CharField(blank=True, max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255)),
                ("product", models.TextField(blank=True)),
                ("vf_id", models.CharField(blank=True, max_length=255)),
                ("vf_name", models.CharField(blank=True, max_length=255)),
                ("vf_fullname", models.TextField(blank=True, null=True)),
                ("vfc_id", models.CharField(blank=True, max_length=255)),
                ("vf_category", models.CharField(blank=True, max_length=255)),
                ("characteristics", models.TextField(blank=True)),
                ("structure", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Viruses Virulence Factor",
                "verbose_name_plural": "MAG Viruses Virulence Factors",
            },
        ),
        migrations.CreateModel(
            name="UnMAGViruses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id_GCA",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "viruses_id_GCF",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("organism_name", models.CharField(blank=True, max_length=255)),
                ("taxonomic_id", models.PositiveIntegerField(blank=True, null=True)),
                ("species", models.CharField(blank=True, max_length=255)),
                (
                    "total_sequence_length",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("gc_content", models.FloatField(blank=True, null=True)),
                ("assembly_level", models.CharField(blank=True, max_length=100)),
                (
                    "total_chromosomes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("contig_n50", models.BigIntegerField(blank=True, null=True)),
                ("scaffold_n50", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Genome",
                "verbose_name_plural": "UnMAG Viruses Genomes",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesAntibioticResistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("product", models.TextField(blank=True)),
                ("arg_database", models.CharField(blank=True, max_length=255)),
                ("cutoff", models.CharField(blank=True, max_length=255)),
                ("hsp_identifier", models.CharField(blank=True, max_length=255)),
                ("best_hit_aro", models.CharField(blank=True, max_length=255)),
                ("best_identities", models.FloatField(blank=True, null=True)),
                ("aro", models.IntegerField(blank=True, null=True)),
                ("drug_class", models.TextField(blank=True)),
                ("resistance_mechanism", models.CharField(blank=True, max_length=255)),
                ("amr_gene_family", models.CharField(blank=True, max_length=255)),
                ("antibiotic", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
                ("snps_in_best_hit_aro", models.TextField(blank=True)),
                ("other_snps", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Antibiotic Resistance Gene",
                "verbose_name_plural": "UnMAG Viruses Antibiotic Resistance Genes",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesAntiCRISPRAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("classification", models.CharField(blank=True, max_length=255)),
                ("aa_length", models.PositiveIntegerField(blank=True, null=True)),
                ("acr_aca", models.TextField(blank=True)),
                ("mge_metadata", models.TextField(blank=True)),
                ("acr_hit_pident", models.CharField(blank=True, max_length=255)),
                ("sequence", models.TextField(blank=True)),
                ("self_target_within_5kb", models.TextField(blank=True)),
                ("self_target_outside_5kb", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Anti-CRISPR Annotation",
                "verbose_name_plural": "UnMAG Viruses Anti-CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesCRISPRCas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("cas_id", models.CharField(blank=True, max_length=100)),
                ("cas_start", models.BigIntegerField(blank=True, null=True)),
                ("cas_end", models.BigIntegerField(blank=True, null=True)),
                ("cas_subtype", models.CharField(blank=True, max_length=255)),
                ("consensus_prediction", models.CharField(blank=True, max_length=255)),
                ("cas_genes", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses CRISPRC CAS Annotation",
                "verbose_name_plural": "UnMAG Viruses CRISPRC CAS Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("orf_prediction_source", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("phase", models.PositiveIntegerField(blank=True, null=True)),
                ("product", models.TextField(blank=True)),
                (
                    "function_prediction_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cog_category", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("preferred_name", models.CharField(blank=True, max_length=255)),
                ("gos", models.TextField(blank=True)),
                ("ec", models.CharField(blank=True, max_length=255)),
                ("kegg_ko", models.TextField(blank=True)),
                ("kegg_pathway", models.TextField(blank=True)),
                ("kegg_module", models.TextField(blank=True)),
                ("kegg_reaction", models.TextField(blank=True)),
                ("kegg_rclass", models.TextField(blank=True)),
                ("brite", models.TextField(blank=True)),
                ("kegg_tc", models.TextField(blank=True)),
                ("cazy", models.TextField(blank=True)),
                ("bigg_reaction", models.TextField(blank=True)),
                ("pfams", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Protein Annotation",
                "verbose_name_plural": "UnMAG Viruses Protein Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "organism_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxonomy_id", models.PositiveIntegerField(blank=True, null=True)),
                ("acellular_root", models.CharField(blank=True, max_length=255)),
                ("realm", models.CharField(blank=True, max_length=255)),
                ("kingdom", models.CharField(blank=True, max_length=255)),
                ("phylum", models.CharField(blank=True, max_length=255)),
                ("class_name", models.CharField(blank=True, max_length=255)),
                ("order", models.CharField(blank=True, max_length=255)),
                ("family", models.CharField(blank=True, max_length=255)),
                ("genus", models.CharField(blank=True, max_length=255)),
                ("species", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Taxonomy",
                "verbose_name_plural": "UnMAG Viruses Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesTransmembraneHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("protein_id", models.CharField(blank=True, max_length=100)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "predicted_tmh_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("expected_aas_in_tmh", models.FloatField(blank=True, null=True)),
                ("expected_first_60_aas", models.FloatField(blank=True, null=True)),
                ("total_prob_n_in", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Transmembrane Helix",
                "verbose_name_plural": "UnMAG Viruses Transmembrane Helices",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesTRNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "trna_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("trna_type", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(0, "forward"), (1, "reverse")], default=0
                    ),
                ),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses tRNA Annotation",
                "verbose_name_plural": "UnMAG Viruses tRNA Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesVirulenceFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viruses_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vf_database", models.CharField(blank=True, max_length=255)),
                ("vfseq_id", models.CharField(blank=True, max_length=255)),
                ("identity", models.FloatField(blank=True, null=True)),
                ("e_value", models.CharField(blank=True, max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255)),
                ("product", models.TextField(blank=True)),
                ("vf_id", models.CharField(blank=True, max_length=255)),
                ("vf_name", models.CharField(blank=True, max_length=255)),
                ("vf_fullname", models.TextField(blank=True, null=True)),
                ("vfc_id", models.CharField(blank=True, max_length=255)),
                ("vf_category", models.CharField(blank=True, max_length=255)),
                ("characteristics", models.TextField(blank=True)),
                ("structure", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Viruses Virulence Factor",
                "verbose_name_plural": "UnMAG Viruses Virulence Factors",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "tmh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helices",
                        to="viruses_database.unmagvirusestransmembranehelices",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnMAG Viruses Helix",
                "verbose_name_plural": "UnMAG Viruses Helices",
            },
        ),
        migrations.CreateModel(
            name="UnMAGVirusesCRISPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crispr_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("crispr_start", models.BigIntegerField(blank=True, null=True)),
                ("crispr_end", models.BigIntegerField(blank=True, null=True)),
                ("crispr_subtype", models.CharField(blank=True, max_length=255)),
                ("repeat_sequence", models.TextField(blank=True)),
                (
                    "cas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CRISPRs",
                        to="viruses_database.unmagvirusescrisprcas",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnMAG Viruses CRISPR Annotation",
                "verbose_name_plural": "UnMAG Viruses CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "tmh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helices",
                        to="viruses_database.magvirusestransmembranehelices",
                    ),
                ),
            ],
            options={
                "verbose_name": "MAG Viruses Helix",
                "verbose_name_plural": "MAG Viruses Helices",
            },
        ),
        migrations.CreateModel(
            name="MAGVirusesCRISPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crispr_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("crispr_start", models.BigIntegerField(blank=True, null=True)),
                ("crispr_end", models.BigIntegerField(blank=True, null=True)),
                ("crispr_subtype", models.CharField(blank=True, max_length=255)),
                ("repeat_sequence", models.TextField(blank=True)),
                (
                    "cas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CRISPRs",
                        to="viruses_database.magvirusescrisprcas",
                    ),
                ),
            ],
            options={
                "verbose_name": "MAG Viruses CRISPR Annotation",
                "verbose_name_plural": "MAG Viruses CRISPR Annotations",
            },
        ),
    ]
