# Generated by Django 4.2 on 2025-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viruses_database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magviruses",
            name="viruses_id_GCA",
        ),
        migrations.RemoveField(
            model_name="magviruses",
            name="viruses_id_GCF",
        ),
        migrations.RemoveField(
            model_name="unmagviruses",
            name="viruses_id_GCA",
        ),
        migrations.RemoveField(
            model_name="unmagviruses",
            name="viruses_id_GCF",
        ),
        migrations.AddField(
            model_name="magviruses",
            name="unique_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="magviruses",
            name="viruses_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unmagviruses",
            name="unique_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="unmagviruses",
            name="viruses_id",
            field=models.TextField(blank=True),
        ),
    ]
