# Generated by Django 4.2 on 2025-05-19 13:23

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viruses_database", "0002_remove_magviruses_viruses_id_gca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magvirusescrisprcas",
            name="cas_subtype",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagvirusescrisprcas",
            name="cas_subtype",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magvirusescrisprcas",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cas_subtype"], name="mv_cas_subtype_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagvirusescrisprcas",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cas_subtype"], name="umv_cas_subtype_gin_idx"
            ),
        ),
    ]
