# Generated by Django 4.2 on 2025-05-20 08:14

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viruses_database", "0003_alter_magvirusescrisprcas_cas_subtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magvirusesantibioticresistance",
            name="drug_class",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagvirusesantibioticresistance",
            name="drug_class",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magvirusesantibioticresistance",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["drug_class"], name="mv_arg_type_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagvirusesantibioticresistance",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["drug_class"], name="umv_arg_type_gin_idx"
            ),
        ),
    ]
