# Generated by Django 4.2 on 2025-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "viruses_database",
            "0004_alter_magvirusesantibioticresistance_drug_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="magviruses",
            name="contig_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magviruses",
            name="scaffold_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magviruses",
            name="taxonomic_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magviruses",
            name="total_chromosomes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagviruses",
            name="contig_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagviruses",
            name="scaffold_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagviruses",
            name="taxonomic_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagviruses",
            name="total_chromosomes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
