# Generated by Django 5.2.3 on 2025-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchaeaMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_55dc39_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ArchaeaMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_03884a_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ArchaeaMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_098ccf_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ArchaeaUnMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_085cf9_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ArchaeaUnMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_5e6b8f_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ArchaeaUnMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_77133d_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_8f7c94_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_013908_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_35d6a8_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaUnMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_d9395d_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaUnMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_d87a4f_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="BacteriaUnMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_260f46_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_84d9e4_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_7923d1_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_e7df0d_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiUnMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_001f44_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiUnMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_91f512_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="FungiUnMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_436ff7_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_a93f53_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_4dba46_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_d13747_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesUnMAGARGIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_062be6_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesUnMAGProteinIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_c0b168_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="VirusesUnMAGTMHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archaea_id", models.CharField(max_length=255, unique=True)),
                ("file_path", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["archaea_id"], name="large_table_archaea_3221f9_idx"
                    )
                ]
            },
        ),
    ]
