# Generated by Django 4.2 on 2025-05-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MAGArchaea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id_GCA",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "archaea_id_GCF",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("organism_name", models.CharField(blank=True, max_length=255)),
                ("taxonomic_id", models.PositiveIntegerField(blank=True, null=True)),
                ("species", models.CharField(blank=True, max_length=255)),
                (
                    "total_sequence_length",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("gc_content", models.FloatField(blank=True, null=True)),
                ("assembly_level", models.CharField(blank=True, max_length=100)),
                (
                    "total_chromosomes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("contig_n50", models.BigIntegerField(blank=True, null=True)),
                ("scaffold_n50", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Genome",
                "verbose_name_plural": "MAG Archaea Genomes",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaAntibioticResistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("product", models.TextField(blank=True)),
                ("arg_database", models.CharField(blank=True, max_length=255)),
                ("cutoff", models.CharField(blank=True, max_length=255)),
                ("hsp_identifier", models.CharField(blank=True, max_length=255)),
                ("best_hit_aro", models.CharField(blank=True, max_length=255)),
                ("best_identities", models.FloatField(blank=True, null=True)),
                ("aro", models.IntegerField(blank=True, null=True)),
                ("drug_class", models.TextField(blank=True)),
                ("resistance_mechanism", models.CharField(blank=True, max_length=255)),
                ("amr_gene_family", models.CharField(blank=True, max_length=255)),
                ("antibiotic", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
                ("snps_in_best_hit_aro", models.TextField(blank=True)),
                ("other_snps", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Antibiotic Resistance Gene",
                "verbose_name_plural": "MAG Archaea Antibiotic Resistance Genes",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaAntiCRISPRAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("classification", models.CharField(blank=True, max_length=255)),
                ("aa_length", models.PositiveIntegerField(blank=True, null=True)),
                ("acr_aca", models.TextField(blank=True)),
                ("mge_metadata", models.TextField(blank=True)),
                ("acr_hit_pident", models.CharField(blank=True, max_length=255)),
                ("sequence", models.TextField(blank=True)),
                ("self_target_within_5kb", models.TextField(blank=True)),
                ("self_target_outside_5kb", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Anti-CRISPR Annotation",
                "verbose_name_plural": "MAG Archaea Anti-CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaCRISPRCas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("cas_id", models.CharField(blank=True, max_length=100)),
                ("cas_start", models.BigIntegerField(blank=True, null=True)),
                ("cas_end", models.BigIntegerField(blank=True, null=True)),
                ("cas_subtype", models.CharField(blank=True, max_length=255)),
                ("consensus_prediction", models.CharField(blank=True, max_length=255)),
                ("cas_genes", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "verbose_name": "MAG Archaea CRISPRC CAS Annotation",
                "verbose_name_plural": "MAG Archaea CRISPRC CAS Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("orf_prediction_source", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("phase", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("product", models.TextField(blank=True)),
                (
                    "function_prediction_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cog_category", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("preferred_name", models.CharField(blank=True, max_length=255)),
                ("gos", models.TextField(blank=True)),
                ("ec", models.CharField(blank=True, max_length=255)),
                ("kegg_ko", models.TextField(blank=True)),
                ("kegg_pathway", models.TextField(blank=True)),
                ("kegg_module", models.TextField(blank=True)),
                ("kegg_reaction", models.TextField(blank=True)),
                ("kegg_rclass", models.TextField(blank=True)),
                ("brite", models.TextField(blank=True)),
                ("kegg_tc", models.TextField(blank=True)),
                ("cazy", models.TextField(blank=True)),
                ("bigg_reaction", models.TextField(blank=True)),
                ("pfams", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Protein Annotation",
                "verbose_name_plural": "MAG Archaea Protein Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaSecondaryMetaboliteRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("most_similar_cluster", models.TextField(blank=True)),
                ("similarity", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "MAG Archaea Secondary Metabolite Region",
                "verbose_name_plural": "MAG Archaea Secondary Metabolite Regions",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaSignalPeptidePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("prediction", models.CharField(blank=True, max_length=255)),
                ("other", models.FloatField(blank=True, null=True)),
                ("sp_sec_spi", models.FloatField(blank=True, null=True)),
                ("lipo_sec_spii", models.FloatField(blank=True, null=True)),
                ("tat_tat_spi", models.FloatField(blank=True, null=True)),
                ("tatlipo_tat_spii", models.FloatField(blank=True, null=True)),
                ("pilin_sec_spiii", models.FloatField(blank=True, null=True)),
                ("cs_position", models.CharField(blank=True, max_length=255)),
                ("cs_probability", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Signal Peptide Prediction",
                "verbose_name_plural": "MAG Archaea Signal Peptide Predictions",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "organism_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxonomy_id", models.PositiveIntegerField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("kingdom", models.CharField(blank=True, max_length=255)),
                ("phylum", models.CharField(blank=True, max_length=255)),
                ("class_name", models.CharField(blank=True, max_length=255)),
                ("order", models.CharField(blank=True, max_length=255)),
                ("family", models.CharField(blank=True, max_length=255)),
                ("genus", models.CharField(blank=True, max_length=255)),
                ("species", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "MAG Archaea Taxonomy",
                "verbose_name_plural": "MAG Archaea Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaTransmembraneHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("protein_id", models.CharField(blank=True, max_length=100)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "predicted_tmh_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("expected_aas_in_tmh", models.FloatField(blank=True, null=True)),
                ("expected_first_60_aas", models.FloatField(blank=True, null=True)),
                ("total_prob_n_in", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Transmembrane Helix",
                "verbose_name_plural": "MAG Archaea Transmembrane Helices",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaTRNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "trna_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("trna_type", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(0, "forward"), (1, "reverse")], default=0
                    ),
                ),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Archaea tRNA Annotation",
                "verbose_name_plural": "MAG Archaea tRNA Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaVirulenceFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vf_database", models.CharField(blank=True, max_length=255)),
                ("vfseq_id", models.CharField(blank=True, max_length=255)),
                ("identity", models.FloatField(blank=True, null=True)),
                ("e_value", models.CharField(blank=True, max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255)),
                ("product", models.TextField(blank=True)),
                ("vf_id", models.CharField(blank=True, max_length=255)),
                ("vf_name", models.CharField(blank=True, max_length=255)),
                ("vf_fullname", models.TextField(blank=True, null=True)),
                ("vfc_id", models.CharField(blank=True, max_length=255)),
                ("vf_category", models.CharField(blank=True, max_length=255)),
                ("characteristics", models.TextField(blank=True)),
                ("structure", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MAG Archaea Virulence Factor",
                "verbose_name_plural": "MAG Archaea Virulence Factors",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id_GCA",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "archaea_id_GCF",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("organism_name", models.CharField(blank=True, max_length=255)),
                ("taxonomic_id", models.PositiveIntegerField(blank=True, null=True)),
                ("species", models.CharField(blank=True, max_length=255)),
                (
                    "total_sequence_length",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("gc_content", models.FloatField(blank=True, null=True)),
                ("assembly_level", models.CharField(blank=True, max_length=100)),
                (
                    "total_chromosomes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("contig_n50", models.BigIntegerField(blank=True, null=True)),
                ("scaffold_n50", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Genome",
                "verbose_name_plural": "UnMAG Archaea Genomes",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaAntibioticResistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("product", models.TextField(blank=True)),
                ("arg_database", models.CharField(blank=True, max_length=255)),
                ("cutoff", models.CharField(blank=True, max_length=255)),
                ("hsp_identifier", models.CharField(blank=True, max_length=255)),
                ("best_hit_aro", models.CharField(blank=True, max_length=255)),
                ("best_identities", models.FloatField(blank=True, null=True)),
                ("aro", models.IntegerField(blank=True, null=True)),
                ("drug_class", models.TextField(blank=True)),
                ("resistance_mechanism", models.CharField(blank=True, max_length=255)),
                ("amr_gene_family", models.CharField(blank=True, max_length=255)),
                ("antibiotic", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
                ("snps_in_best_hit_aro", models.TextField(blank=True)),
                ("other_snps", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Antibiotic Resistance Gene",
                "verbose_name_plural": "UnMAG Archaea Antibiotic Resistance Genes",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaAntiCRISPRAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("classification", models.CharField(blank=True, max_length=255)),
                ("aa_length", models.PositiveIntegerField(blank=True, null=True)),
                ("acr_aca", models.TextField(blank=True)),
                ("mge_metadata", models.TextField(blank=True)),
                ("acr_hit_pident", models.CharField(blank=True, max_length=255)),
                ("sequence", models.TextField(blank=True)),
                ("self_target_within_5kb", models.TextField(blank=True)),
                ("self_target_outside_5kb", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Anti-CRISPR Annotation",
                "verbose_name_plural": "UnMAG Archaea Anti-CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaCRISPRCas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("cas_id", models.CharField(blank=True, max_length=100)),
                ("cas_start", models.BigIntegerField(blank=True, null=True)),
                ("cas_end", models.BigIntegerField(blank=True, null=True)),
                ("cas_subtype", models.CharField(blank=True, max_length=255)),
                ("consensus_prediction", models.CharField(blank=True, max_length=255)),
                ("cas_genes", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea CRISPRC CAS Annotation",
                "verbose_name_plural": "UnMAG Archaea CRISPRC CAS Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaProtein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("orf_prediction_source", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(choices=[(0, "+"), (1, "-")], default=0),
                ),
                ("phase", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("product", models.TextField(blank=True)),
                (
                    "function_prediction_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cog_category", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("preferred_name", models.CharField(blank=True, max_length=255)),
                ("gos", models.TextField(blank=True)),
                ("ec", models.CharField(blank=True, max_length=255)),
                ("kegg_ko", models.TextField(blank=True)),
                ("kegg_pathway", models.TextField(blank=True)),
                ("kegg_module", models.TextField(blank=True)),
                ("kegg_reaction", models.TextField(blank=True)),
                ("kegg_rclass", models.TextField(blank=True)),
                ("brite", models.TextField(blank=True)),
                ("kegg_tc", models.TextField(blank=True)),
                ("cazy", models.TextField(blank=True)),
                ("bigg_reaction", models.TextField(blank=True)),
                ("pfams", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Protein Annotation",
                "verbose_name_plural": "UnMAG Archaea Protein Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaSecondaryMetaboliteRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("most_similar_cluster", models.TextField(blank=True)),
                ("similarity", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Secondary Metabolite Region",
                "verbose_name_plural": "UnMAG Archaea Secondary Metabolite Regions",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaSignalPeptidePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("prediction", models.CharField(blank=True, max_length=255)),
                ("other", models.FloatField(blank=True, null=True)),
                ("sp_sec_spi", models.FloatField(blank=True, null=True)),
                ("lipo_sec_spii", models.FloatField(blank=True, null=True)),
                ("tat_tat_spi", models.FloatField(blank=True, null=True)),
                ("tatlipo_tat_spii", models.FloatField(blank=True, null=True)),
                ("pilin_sec_spiii", models.FloatField(blank=True, null=True)),
                ("cs_position", models.CharField(blank=True, max_length=255)),
                ("cs_probability", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Signal Peptide Prediction",
                "verbose_name_plural": "UnMAG Archaea Signal Peptide Predictions",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "organism_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxonomy_id", models.PositiveIntegerField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("kingdom", models.CharField(blank=True, max_length=255)),
                ("phylum", models.CharField(blank=True, max_length=255)),
                ("class_name", models.CharField(blank=True, max_length=255)),
                ("order", models.CharField(blank=True, max_length=255)),
                ("family", models.CharField(blank=True, max_length=255)),
                ("genus", models.CharField(blank=True, max_length=255)),
                ("species", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Taxonomy",
                "verbose_name_plural": "UnMAG Archaea Taxonomies",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaTransmembraneHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                ("protein_id", models.CharField(blank=True, max_length=100)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "predicted_tmh_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("expected_aas_in_tmh", models.FloatField(blank=True, null=True)),
                ("expected_first_60_aas", models.FloatField(blank=True, null=True)),
                ("total_prob_n_in", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Transmembrane Helix",
                "verbose_name_plural": "UnMAG Archaea Transmembrane Helices",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaTRNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "trna_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("trna_type", models.CharField(blank=True, max_length=255)),
                ("start", models.PositiveIntegerField(blank=True, null=True)),
                ("end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(0, "forward"), (1, "reverse")], default=0
                    ),
                ),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea tRNA Annotation",
                "verbose_name_plural": "UnMAG Archaea tRNA Annotations",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaVirulenceFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archaea_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("contig_id", models.CharField(blank=True, max_length=100)),
                (
                    "protein_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vf_database", models.CharField(blank=True, max_length=255)),
                ("vfseq_id", models.CharField(blank=True, max_length=255)),
                ("identity", models.FloatField(blank=True, null=True)),
                ("e_value", models.CharField(blank=True, max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255)),
                ("product", models.TextField(blank=True)),
                ("vf_id", models.CharField(blank=True, max_length=255)),
                ("vf_name", models.CharField(blank=True, max_length=255)),
                ("vf_fullname", models.TextField(blank=True, null=True)),
                ("vfc_id", models.CharField(blank=True, max_length=255)),
                ("vf_category", models.CharField(blank=True, max_length=255)),
                ("characteristics", models.TextField(blank=True)),
                ("structure", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                ("sequence", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "UnMAG Archaea Virulence Factor",
                "verbose_name_plural": "UnMAG Archaea Virulence Factors",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "tmh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helices",
                        to="archaea_database.unmagarchaeatransmembranehelices",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnMAG Archaea Helix",
                "verbose_name_plural": "UnMAG Archaea Helices",
            },
        ),
        migrations.CreateModel(
            name="UnMAGArchaeaCRISPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crispr_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("crispr_start", models.BigIntegerField(blank=True, null=True)),
                ("crispr_end", models.BigIntegerField(blank=True, null=True)),
                ("crispr_subtype", models.CharField(blank=True, max_length=255)),
                ("repeat_sequence", models.TextField(blank=True)),
                (
                    "cas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CRISPRs",
                        to="archaea_database.unmagarchaeacrisprcas",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnMAG Archaea CRISPR Annotation",
                "verbose_name_plural": "UnMAG Archaea CRISPR Annotations",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaHelices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255)),
                ("start", models.IntegerField(blank=True, null=True)),
                ("end", models.IntegerField(blank=True, null=True)),
                (
                    "tmh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helices",
                        to="archaea_database.magarchaeatransmembranehelices",
                    ),
                ),
            ],
            options={
                "verbose_name": "MAG Archaea Helix",
                "verbose_name_plural": "MAG Archaea Helices",
            },
        ),
        migrations.CreateModel(
            name="MAGArchaeaCRISPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crispr_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("crispr_start", models.BigIntegerField(blank=True, null=True)),
                ("crispr_end", models.BigIntegerField(blank=True, null=True)),
                ("crispr_subtype", models.CharField(blank=True, max_length=255)),
                ("repeat_sequence", models.TextField(blank=True)),
                (
                    "cas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CRISPRs",
                        to="archaea_database.magarchaeacrisprcas",
                    ),
                ),
            ],
            options={
                "verbose_name": "MAG Archaea CRISPR Annotation",
                "verbose_name_plural": "MAG Archaea CRISPR Annotations",
            },
        ),
    ]
