# Generated by Django 4.2 on 2025-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archaea_database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magarchaea",
            name="total_chromosomes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magarchaeaprotein",
            name="phase",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagarchaea",
            name="total_chromosomes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagarchaeaprotein",
            name="phase",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
