# Generated by Django 4.2 on 2025-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archaea_database", "0002_alter_magarchaea_total_chromosomes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magarchaea",
            name="archaea_id_GCA",
        ),
        migrations.RemoveField(
            model_name="magarchaea",
            name="archaea_id_GCF",
        ),
        migrations.RemoveField(
            model_name="unmagarchaea",
            name="archaea_id_GCA",
        ),
        migrations.RemoveField(
            model_name="unmagarchaea",
            name="archaea_id_GCF",
        ),
        migrations.AddField(
            model_name="magarchaea",
            name="archaea_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="magarchaea",
            name="unique_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="unmagarchaea",
            name="archaea_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unmagarchaea",
            name="unique_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
