# Generated by Django 4.2 on 2025-05-20 06:08

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archaea_database", "0004_alter_magarchaeacrisprcas_cas_subtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magarchaeasecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagarchaeasecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magarchaeasecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="ma_sm_type_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagarchaeasecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="uma_sm_type_gin_idx"
            ),
        ),
    ]
