# Generated by Django 4.2 on 2025-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "archaea_database",
            "0006_alter_magarchaeaantibioticresistance_drug_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="unmagarchaea",
            name="taxonomic_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
