# Generated by Django 4.2 on 2025-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archaea_database", "0007_alter_unmagarchaea_taxonomic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unmagarchaea",
            name="contig_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagarchaea",
            name="scaffold_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
