# Generated by Django 4.2 on 2025-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archaea_database", "0009_alter_unmagarchaea_total_chromosomes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magarchaea",
            name="contig_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magarchaea",
            name="scaffold_n50",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magarchaea",
            name="taxonomic_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magarchaea",
            name="total_chromosomes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
