from django.urls import path

from viruses_database.views import genomes_views, proteins_views, tRNAs_views, crisprcas_views, anti_cripsr_views, \
    virulence_factor_views, antibiotic_resistance_views, transmembrane_helices_views

urlpatterns = [
    path('genomes', genomes_views.VirusesGenomesView.as_view()),
    path('genomes_unmag', genomes_views.UnMAGVirusesGenomesView.as_view()),
    path('genomes_filter_options', genomes_views.VirusesGenomesFilterOptionsView.as_view()),
    path('genomes_filter_options_unmag', genomes_views.UnMAGVirusesGenomesFilterOptionsView.as_view()),
    path('genome_single_download', genomes_views.VirusesGenomesSingleDownloadView.as_view()),
    path('genome_single_download_unmag', genomes_views.UnMAGVirusesGenomesSingleDownloadView.as_view()),
    path('genome_batch_download', genomes_views.VirusesGenomesBatchDownloadView.as_view()),
    path('genome_batch_download_unmag', genomes_views.UnMAGVirusesGenomesBatchDownloadView.as_view()),
    path('proteins', proteins_views.VirusesProteinsView.as_view()),
    path('proteins_unmag', proteins_views.UnMAGVirusesProteinsView.as_view()),
    path('proteins_filter_options', proteins_views.VirusesProteinsFilterOptionsView.as_view()),
    path('proteins_filter_options_unmag', proteins_views.UnMAGVirusesProteinsFilterOptionsView.as_view()),
    path('protein_single_download', proteins_views.VirusesProteinsSingleDownloadView.as_view()),
    path('protein_single_download_unmag', proteins_views.UnMAGVirusesProteinsSingleDownloadView.as_view()),
    path('protein_batch_download', proteins_views.VirusesProteinsBatchDownloadView.as_view()),
    path('protein_batch_download_unmag', proteins_views.UnMAGVirusesProteinsBatchDownloadView.as_view()),
    path('tRNAs', tRNAs_views.VirusesTRNAsView.as_view()),
    path('tRNAs_unmag', tRNAs_views.UnMAGVirusesTRNAsView.as_view()),
    path('tRNAs_filter_options', tRNAs_views.VirusesTRNAFilterOptionsView.as_view()),
    path('tRNAs_filter_options_unmag', tRNAs_views.UnMAGVirusesTRNAFilterOptionsView.as_view()),
    path('tRNA_single_download', tRNAs_views.VirusesTRNASingleDownloadView.as_view()),
    path('tRNA_single_download_unmag', tRNAs_views.UnMAGVirusesTRNASingleDownloadView.as_view()),
    path('tRNA_batch_download', tRNAs_views.VirusesTRNABatchDownloadView.as_view()),
    path('tRNA_batch_download_unmag', tRNAs_views.UnMAGVirusesTRNABatchDownloadView.as_view()),
    path('CRISPR_Cas_systems', crisprcas_views.VirusesCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_unmag', crisprcas_views.UnMAGVirusesCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_filter_options', crisprcas_views.VirusesCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_systems_filter_options_unmag',
         crisprcas_views.UnMAGVirusesCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_system_single_download', crisprcas_views.VirusesCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_single_download_unmag',
         crisprcas_views.UnMAGVirusesCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download', crisprcas_views.VirusesCRISPRCasSystemsBatchDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download_unmag',
         crisprcas_views.UnMAGVirusesCRISPRCasSystemsBatchDownloadView.as_view()),
    path('anti_crispr_annotations', anti_cripsr_views.VirusesAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_unmag', anti_cripsr_views.UnMAGVirusesAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_filter_options',
         anti_cripsr_views.VirusesAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotations_filter_options_unmag',
         anti_cripsr_views.UnMAGVirusesAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotation_single_download',
         anti_cripsr_views.VirusesAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_single_download_unmag',
         anti_cripsr_views.UnMAGVirusesAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download',
         anti_cripsr_views.VirusesAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download_unmag',
         anti_cripsr_views.UnMAGVirusesAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('virulence_factors', virulence_factor_views.VirusesVirulenceFactorsView.as_view()),
    path('virulence_factors_unmag', virulence_factor_views.UnMAGVirusesVirulenceFactorsView.as_view()),
    path('virulence_factors_filter_options', virulence_factor_views.VirusesVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factors_filter_options_unmag',
         virulence_factor_views.UnMAGVirusesVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factor_single_download', virulence_factor_views.VirusesVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_single_download_unmag',
         virulence_factor_views.UnMAGVirusesVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_batch_download', virulence_factor_views.VirusesVirulenceFactorsBatchDownloadView.as_view()),
    path('virulence_factor_batch_download_unmag',
         virulence_factor_views.UnMAGVirusesVirulenceFactorsBatchDownloadView.as_view()),
    path('antibiotic_resistances', antibiotic_resistance_views.VirusesAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_unmag', antibiotic_resistance_views.UnMAGVirusesAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_filter_options',
         antibiotic_resistance_views.VirusesAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistances_filter_options_unmag',
         antibiotic_resistance_views.UnMAGVirusesAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistance_single_download',
         antibiotic_resistance_views.VirusesAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_single_download_unmag',
         antibiotic_resistance_views.UnMAGVirusesAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_batch_download',
         antibiotic_resistance_views.VirusesAntibioticResistancesBatchDownloadView.as_view()),
    path('antibiotic_resistance_batch_download_unmag',
         antibiotic_resistance_views.UnMAGVirusesAntibioticResistancesBatchDownloadView.as_view()),
    path('transmembrane_helices', transmembrane_helices_views.VirusesTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_unmag', transmembrane_helices_views.UnMAGVirusesTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_filter_options',
         transmembrane_helices_views.VirusesTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helices_filter_options_unmag',
         transmembrane_helices_views.UnMAGVirusesTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helice_single_download',
         transmembrane_helices_views.VirusesTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_single_download_unmag',
         transmembrane_helices_views.UnMAGVirusesTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_batch_download',
         transmembrane_helices_views.VirusesTransmembraneHelicesBatchDownloadView.as_view()),
    path('transmembrane_helice_batch_download_unmag',
         transmembrane_helices_views.UnMAGVirusesTransmembraneHelicesBatchDownloadView.as_view()),
    path('genome_detail', genomes_views.VirusesGenomeDetailView.as_view()),
    path('genome_detail_unmag', genomes_views.UnVirusesGenomeDetailView.as_view()),
    path('genome_detail_proteins', genomes_views.VirusesGenomeProteinsView.as_view()),
    path('genome_detail_proteins_unmag', genomes_views.UnVirusesGenomeProteinsView.as_view()),
    path('genome_detail_tRNAs', genomes_views.VirusesGenomeTRNAsView.as_view()),
    path('genome_detail_tRNAs_unmag', genomes_views.UnMAGVirusesGenomeTRNAsView.as_view()),
    path('genome_detail_cripsr', genomes_views.VirusesGenomeCRISPRCasView.as_view()),
    path('genome_detail_crispr_unmag', genomes_views.UnMAGVirusesGenomeCRISPRCasView.as_view()),
    path('genome_detail_anti_crispr', genomes_views.VirusesGenomeAntiCRISPRView.as_view()),
    path('genome_detail_anti_crispr_unmag', genomes_views.UnMAGVirusesGenomeAntiCRISPRView.as_view()),
    path('genome_detail_virulence_factors', genomes_views.VirusesGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_virulence_factors_unmag', genomes_views.UnMAGVirusesGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_antibiotic_resistance', genomes_views.VirusesGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_antibiotic_resistance_unmag',
         genomes_views.UnMAGVirusesGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_transmembrane_helices', genomes_views.VirusesGenomeTransmembraneHelicesView.as_view()),
    path('genome_detail_transmembrane_helices_unmag',
         genomes_views.UnMAGVirusesGenomeTransmembraneHelicesView.as_view()
         ),
    path('genome_fasta', genomes_views.VirusesGenomeFASTAView.as_view()),
    path('genome_fasta_unmag', genomes_views.UnMAGVirusesGenomeFASTAView.as_view()),
]
