# Generated by Django 4.2 on 2025-06-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe_database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrobeFilterOptionsNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
