from django.urls import path

from fungi_database.views import genomes_views, proteins_views, tRNAs_views, secondary_metabolites_views, \
    signal_peptide_views, virulence_factor_views, antibiotic_resistance_views, transmembrane_helices_views

urlpatterns = [
    path('genomes', genomes_views.FungiGenomesView.as_view()),
    path('genomes_unmag', genomes_views.UnMAGFungiGenomesView.as_view()),
    path('genomes_filter_options', genomes_views.FungiGenomesFilterOptionsView.as_view()),
    path('genomes_filter_options_unmag', genomes_views.UnMAGFungiGenomesFilterOptionsView.as_view()),
    path('genome_single_download', genomes_views.FungiGenomesSingleDownloadView.as_view()),
    path('genome_single_download_unmag', genomes_views.UnMAGFungiGenomesSingleDownloadView.as_view()),
    path('genome_batch_download', genomes_views.FungiGenomesBatchDownloadView.as_view()),
    path('genome_batch_download_unmag', genomes_views.UnMAGFungiGenomesBatchDownloadView.as_view()),
    path('proteins', proteins_views.FungiProteinsView.as_view()),
    path('proteins_unmag', proteins_views.UnMAGFungiProteinsView.as_view()),
    path('proteins_filter_options', proteins_views.FungiProteinsFilterOptionsView.as_view()),
    path('proteins_filter_options_unmag', proteins_views.UnMAGFungiProteinsFilterOptionsView.as_view()),
    path('protein_single_download', proteins_views.FungiProteinsSingleDownloadView.as_view()),
    path('protein_single_download_unmag', proteins_views.UnMAGFungiProteinsSingleDownloadView.as_view()),
    path('protein_batch_download', proteins_views.FungiProteinsBatchDownloadView.as_view()),
    path('protein_batch_download_unmag', proteins_views.UnMAGFungiProteinsBatchDownloadView.as_view()),
    path('tRNAs', tRNAs_views.FungiTRNAsView.as_view()),
    path('tRNAs_unmag', tRNAs_views.UnMAGFungiTRNAsView.as_view()),
    path('tRNAs_filter_options', tRNAs_views.FungiTRNAFilterOptionsView.as_view()),
    path('tRNAs_filter_options_unmag', tRNAs_views.UnMAGFungiTRNAFilterOptionsView.as_view()),
    path('tRNA_single_download', tRNAs_views.FungiTRNASingleDownloadView.as_view()),
    path('tRNA_single_download_unmag', tRNAs_views.UnMAGFungiTRNASingleDownloadView.as_view()),
    path('tRNA_batch_download', tRNAs_views.FungiTRNABatchDownloadView.as_view()),
    path('tRNA_batch_download_unmag', tRNAs_views.UnMAGFungiTRNABatchDownloadView.as_view()),
    path('secondary_metabolites', secondary_metabolites_views.FungiSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_unmag', secondary_metabolites_views.UnMAGFungiSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_filter_options',
         secondary_metabolites_views.FungiSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolites_filter_options_unmag',
         secondary_metabolites_views.UnMAGFungiSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolite_single_download',
         secondary_metabolites_views.FungiSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_single_download_unmag',
         secondary_metabolites_views.UnMAGFungiSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_batch_download',
         secondary_metabolites_views.FungiSecondaryMetabolitesBatchDownloadView.as_view()),
    path('secondary_metabolite_batch_download_unmag',
         secondary_metabolites_views.UnMAGFungiSecondaryMetabolitesBatchDownloadView.as_view()),
    path('signal_peptides', signal_peptide_views.FungiSignalPeptidesView.as_view()),
    path('signal_peptides_unmag', signal_peptide_views.UnMAGFungiSignalPeptidesView.as_view()),
    path('signal_peptides_filter_options', signal_peptide_views.FungiSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptides_filter_options_unmag',
         signal_peptide_views.UnMAGFungiSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptide_single_download', signal_peptide_views.FungiSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_single_download_unmag',
         signal_peptide_views.UnMAGFungiSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_batch_download', signal_peptide_views.FungiSignalPeptidesBatchDownloadView.as_view()),
    path('signal_peptide_batch_download_unmag',
         signal_peptide_views.UnMAGFungiSignalPeptidesBatchDownloadView.as_view()),
    path('virulence_factors', virulence_factor_views.FungiVirulenceFactorsView.as_view()),
    path('virulence_factors_unmag', virulence_factor_views.UnMAGFungiVirulenceFactorsView.as_view()),
    path('virulence_factors_filter_options', virulence_factor_views.FungiVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factors_filter_options_unmag',
         virulence_factor_views.UnMAGFungiVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factor_single_download', virulence_factor_views.FungiVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_single_download_unmag',
         virulence_factor_views.UnMAGFungiVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_batch_download', virulence_factor_views.FungiVirulenceFactorsBatchDownloadView.as_view()),
    path('virulence_factor_batch_download_unmag',
         virulence_factor_views.UnMAGFungiVirulenceFactorsBatchDownloadView.as_view()),
    path('antibiotic_resistances', antibiotic_resistance_views.FungiAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_unmag', antibiotic_resistance_views.UnMAGFungiAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_filter_options',
         antibiotic_resistance_views.FungiAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistances_filter_options_unmag',
         antibiotic_resistance_views.UnMAGFungiAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistance_single_download',
         antibiotic_resistance_views.FungiAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_single_download_unmag',
         antibiotic_resistance_views.UnMAGFungiAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_batch_download',
         antibiotic_resistance_views.FungiAntibioticResistancesBatchDownloadView.as_view()),
    path('antibiotic_resistance_batch_download_unmag',
         antibiotic_resistance_views.UnMAGFungiAntibioticResistancesBatchDownloadView.as_view()),
    path('transmembrane_helices', transmembrane_helices_views.FungiTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_unmag', transmembrane_helices_views.UnMAGFungiTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_filter_options',
         transmembrane_helices_views.FungiTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helices_filter_options_unmag',
         transmembrane_helices_views.UnMAGFungiTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helice_single_download',
         transmembrane_helices_views.FungiTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_single_download_unmag',
         transmembrane_helices_views.UnMAGFungiTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_batch_download',
         transmembrane_helices_views.FungiTransmembraneHelicesBatchDownloadView.as_view()),
    path('transmembrane_helice_batch_download_unmag',
         transmembrane_helices_views.UnMAGFungiTransmembraneHelicesBatchDownloadView.as_view()),
    path('genome_detail', genomes_views.FungiGenomeDetailView.as_view()),
    path('genome_detail_unmag', genomes_views.UnFungiGenomeDetailView.as_view()),
    path('genome_detail_proteins', genomes_views.FungiGenomeProteinsView.as_view()),
    path('genome_detail_proteins_unmag', genomes_views.UnFungiGenomeProteinsView.as_view()),
    path('genome_detail_tRNAs', genomes_views.FungiGenomeTRNAsView.as_view()),
    path('genome_detail_tRNAs_unmag', genomes_views.UnMAGFungiGenomeTRNAsView.as_view()),
    path('genome_detail_secondary_metabolites', genomes_views.FungiGenomeSecondaryMetabolitesView.as_view()),
    path('genome_detail_secondary_metabolites_unmag',
         genomes_views.UnMAGFungiGenomeSecondaryMetabolitesView.as_view()),
    path('genome_detail_signal_peptides', genomes_views.FungiGenomeSignalPeptidesView.as_view()),
    path('genome_detail_signal_peptides_unmag', genomes_views.UnMAGFungiGenomeSignalPeptidesView.as_view()),
    path('genome_detail_virulence_factors', genomes_views.FungiGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_virulence_factors_unmag', genomes_views.UnMAGFungiGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_antibiotic_resistance', genomes_views.FungiGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_antibiotic_resistance_unmag',
         genomes_views.UnMAGFungiGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_transmembrane_helices', genomes_views.FungiGenomeTransmembraneHelicesView.as_view()),
    path('genome_detail_transmembrane_helices_unmag',
         genomes_views.UnMAGFungiGenomeTransmembraneHelicesView.as_view()
         ),
    path('genome_fasta', genomes_views.FungiGenomeFASTAView.as_view()),
    path('genome_fasta_unmag', genomes_views.UnMAGFungiGenomeFASTAView.as_view()),
]
