# Generated by Django 4.2 on 2025-05-19 13:23

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacteria_database", "0002_remove_magbacteria_bacteria_id_gca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magbacteriacrisprcas",
            name="cas_subtype",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagbacteriacrisprcas",
            name="cas_subtype",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magbacteriacrisprcas",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cas_subtype"], name="mb_cas_subtype_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagbacteriacrisprcas",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cas_subtype"], name="umb_cas_subtype_gin_idx"
            ),
        ),
    ]
