# Generated by Django 4.2 on 2025-05-20 06:08

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacteria_database", "0003_alter_magbacteriacrisprcas_cas_subtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magbacteriasecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagbacteriasecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magbacteriasecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="mb_sm_type_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagbacteriasecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="umb_sm_type_gin_idx"
            ),
        ),
    ]
