from django.urls import path

from bacteria_database.views import genomes_views, proteins_views, tRNAs_views, crisprcas_views, anti_cripsr_views, \
    secondary_metabolites_views, signal_peptide_views, virulence_factor_views, antibiotic_resistance_views, \
    transmembrane_helices_views

urlpatterns = [
    path('genomes', genomes_views.BacteriaGenomesView.as_view()),
    path('genomes_unmag', genomes_views.UnMAGBacteriaGenomesView.as_view()),
    path('genomes_filter_options', genomes_views.BacteriaGenomesFilterOptionsView.as_view()),
    path('genomes_filter_options_unmag', genomes_views.UnMAGBacteriaGenomesFilterOptionsView.as_view()),
    path('genome_single_download', genomes_views.BacteriaGenomesSingleDownloadView.as_view()),
    path('genome_single_download_unmag', genomes_views.UnMAGBacteriaGenomesSingleDownloadView.as_view()),
    path('genome_batch_download', genomes_views.BacteriaGenomesBatchDownloadView.as_view()),
    path('genome_batch_download_unmag', genomes_views.UnMAGBacteriaGenomesBatchDownloadView.as_view()),
    path('proteins', proteins_views.BacteriaProteinsView.as_view()),
    path('proteins_unmag', proteins_views.UnMAGBacteriaProteinsView.as_view()),
    path('proteins_filter_options', proteins_views.BacteriaProteinsFilterOptionsView.as_view()),
    path('proteins_filter_options_unmag', proteins_views.UnMAGBacteriaProteinsFilterOptionsView.as_view()),
    path('protein_single_download', proteins_views.BacteriaProteinsSingleDownloadView.as_view()),
    path('protein_single_download_unmag', proteins_views.UnMAGBacteriaProteinsSingleDownloadView.as_view()),
    path('protein_batch_download', proteins_views.BacteriaProteinsBatchDownloadView.as_view()),
    path('protein_batch_download_unmag', proteins_views.UnMAGBacteriaProteinsBatchDownloadView.as_view()),
    path('tRNAs', tRNAs_views.BacteriaTRNAsView.as_view()),
    path('tRNAs_unmag', tRNAs_views.UnMAGBacteriaTRNAsView.as_view()),
    path('tRNAs_filter_options', tRNAs_views.BacteriaTRNAFilterOptionsView.as_view()),
    path('tRNAs_filter_options_unmag', tRNAs_views.UnMAGBacteriaTRNAFilterOptionsView.as_view()),
    path('tRNA_single_download', tRNAs_views.BacteriaTRNASingleDownloadView.as_view()),
    path('tRNA_single_download_unmag', tRNAs_views.UnMAGBacteriaTRNASingleDownloadView.as_view()),
    path('tRNA_batch_download', tRNAs_views.BacteriaTRNABatchDownloadView.as_view()),
    path('tRNA_batch_download_unmag', tRNAs_views.UnMAGBacteriaTRNABatchDownloadView.as_view()),
    path('CRISPR_Cas_systems', crisprcas_views.BacteriaCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_unmag', crisprcas_views.UnMAGBacteriaCRISPRCasSystemsView.as_view()),
    path('CRISPR_Cas_systems_filter_options', crisprcas_views.BacteriaCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_systems_filter_options_unmag',
         crisprcas_views.UnMAGBacteriaCRISPRCasSystemsFilterOptionsView.as_view()),
    path('CRISPR_Cas_system_single_download', crisprcas_views.BacteriaCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_single_download_unmag',
         crisprcas_views.UnMAGBacteriaCRISPRCasSystemsSingleDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download', crisprcas_views.BacteriaCRISPRCasSystemsBatchDownloadView.as_view()),
    path('CRISPR_Cas_system_batch_download_unmag',
         crisprcas_views.UnMAGBacteriaCRISPRCasSystemsBatchDownloadView.as_view()),
    path('anti_crispr_annotations', anti_cripsr_views.BacteriaAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_unmag', anti_cripsr_views.UnMAGBacteriaAntiCRISPRAnnotationsView.as_view()),
    path('anti_crispr_annotations_filter_options',
         anti_cripsr_views.BacteriaAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotations_filter_options_unmag',
         anti_cripsr_views.UnMAGBacteriaAntiCRISPRAnnotationsFilterOptionsView.as_view()),
    path('anti_crispr_annotation_single_download',
         anti_cripsr_views.BacteriaAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_single_download_unmag',
         anti_cripsr_views.UnMAGBacteriaAntiCRISPRAnnotationsSingleDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download',
         anti_cripsr_views.BacteriaAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('anti_crispr_annotation_batch_download_unmag',
         anti_cripsr_views.UnMAGBacteriaAntiCRISPRAnnotationsBatchDownloadView.as_view()),
    path('secondary_metabolites', secondary_metabolites_views.BacteriaSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_unmag', secondary_metabolites_views.UnMAGBacteriaSecondaryMetabolitesView.as_view()),
    path('secondary_metabolites_filter_options',
         secondary_metabolites_views.BacteriaSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolites_filter_options_unmag',
         secondary_metabolites_views.UnMAGBacteriaSecondaryMetabolitesFilterOptionsView.as_view()),
    path('secondary_metabolite_single_download',
         secondary_metabolites_views.BacteriaSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_single_download_unmag',
         secondary_metabolites_views.UnMAGBacteriaSecondaryMetabolitesSingleDownloadView.as_view()),
    path('secondary_metabolite_batch_download',
         secondary_metabolites_views.BacteriaSecondaryMetabolitesBatchDownloadView.as_view()),
    path('secondary_metabolite_batch_download_unmag',
         secondary_metabolites_views.UnMAGBacteriaSecondaryMetabolitesBatchDownloadView.as_view()),
    path('signal_peptides', signal_peptide_views.BacteriaSignalPeptidesView.as_view()),
    path('signal_peptides_unmag', signal_peptide_views.UnMAGBacteriaSignalPeptidesView.as_view()),
    path('signal_peptides_filter_options', signal_peptide_views.BacteriaSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptides_filter_options_unmag',
         signal_peptide_views.UnMAGBacteriaSignalPeptidesFilterOptionsView.as_view()),
    path('signal_peptide_single_download', signal_peptide_views.BacteriaSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_single_download_unmag',
         signal_peptide_views.UnMAGBacteriaSignalPeptidesSingleDownloadView.as_view()),
    path('signal_peptide_batch_download', signal_peptide_views.BacteriaSignalPeptidesBatchDownloadView.as_view()),
    path('signal_peptide_batch_download_unmag',
         signal_peptide_views.UnMAGBacteriaSignalPeptidesBatchDownloadView.as_view()),
    path('virulence_factors', virulence_factor_views.BacteriaVirulenceFactorsView.as_view()),
    path('virulence_factors_unmag', virulence_factor_views.UnMAGBacteriaVirulenceFactorsView.as_view()),
    path('virulence_factors_filter_options',
         virulence_factor_views.BacteriaVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factors_filter_options_unmag',
         virulence_factor_views.UnMAGBacteriaVirulenceFactorsFilterOptionsView.as_view()),
    path('virulence_factor_single_download',
         virulence_factor_views.BacteriaVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_single_download_unmag',
         virulence_factor_views.UnMAGBacteriaVirulenceFactorSingleDownloadView.as_view()),
    path('virulence_factor_batch_download', virulence_factor_views.BacteriaVirulenceFactorsBatchDownloadView.as_view()),
    path('virulence_factor_batch_download_unmag',
         virulence_factor_views.UnMAGBacteriaVirulenceFactorsBatchDownloadView.as_view()),
    path('antibiotic_resistances', antibiotic_resistance_views.BacteriaAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_unmag', antibiotic_resistance_views.UnMAGBacteriaAntibioticResistancesView.as_view()),
    path('antibiotic_resistances_filter_options',
         antibiotic_resistance_views.BacteriaAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistances_filter_options_unmag',
         antibiotic_resistance_views.UnMAGBacteriaAntibioticResistancesFilterOptionsView.as_view()),
    path('antibiotic_resistance_single_download',
         antibiotic_resistance_views.BacteriaAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_single_download_unmag',
         antibiotic_resistance_views.UnMAGBacteriaAntibioticResistancesSingleDownloadView.as_view()),
    path('antibiotic_resistance_batch_download',
         antibiotic_resistance_views.BacteriaAntibioticResistancesBatchDownloadView.as_view()),
    path('antibiotic_resistance_batch_download_unmag',
         antibiotic_resistance_views.UnMAGBacteriaAntibioticResistancesBatchDownloadView.as_view()),
    path('transmembrane_helices', transmembrane_helices_views.BacteriaTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_unmag', transmembrane_helices_views.UnMAGBacteriaTransmembraneHelicesView.as_view()),
    path('transmembrane_helices_filter_options',
         transmembrane_helices_views.BacteriaTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helices_filter_options_unmag',
         transmembrane_helices_views.UnMAGBacteriaTransmembraneHelicesFilterOptionsView.as_view()),
    path('transmembrane_helice_single_download',
         transmembrane_helices_views.BacteriaTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_single_download_unmag',
         transmembrane_helices_views.UnMAGBacteriaTransmembraneHelicesSingleDownloadView.as_view()),
    path('transmembrane_helice_batch_download',
         transmembrane_helices_views.BacteriaTransmembraneHelicesBatchDownloadView.as_view()),
    path('transmembrane_helice_batch_download_unmag',
         transmembrane_helices_views.UnMAGBacteriaTransmembraneHelicesBatchDownloadView.as_view()),
    path('genome_detail', genomes_views.BacteriaGenomeDetailView.as_view()),
    path('genome_detail_unmag', genomes_views.UnBacteriaGenomeDetailView.as_view()),
    path('genome_detail_proteins', genomes_views.BacteriaGenomeProteinsView.as_view()),
    path('genome_detail_proteins_unmag', genomes_views.UnBacteriaGenomeProteinsView.as_view()),
    path('genome_detail_tRNAs', genomes_views.BacteriaGenomeTRNAsView.as_view()),
    path('genome_detail_tRNAs_unmag', genomes_views.UnMAGBacteriaGenomeTRNAsView.as_view()),
    path('genome_detail_cripsr', genomes_views.BacteriaGenomeCRISPRCasView.as_view()),
    path('genome_detail_crispr_unmag', genomes_views.UnMAGBacteriaGenomeCRISPRCasView.as_view()),
    path('genome_detail_anti_crispr', genomes_views.BacteriaGenomeAntiCRISPRView.as_view()),
    path('genome_detail_anti_crispr_unmag', genomes_views.UnMAGBacteriaGenomeAntiCRISPRView.as_view()),
    path('genome_detail_secondary_metabolites', genomes_views.BacteriaGenomeSecondaryMetabolitesView.as_view()),
    path('genome_detail_secondary_metabolites_unmag',
         genomes_views.UnMAGBacteriaGenomeSecondaryMetabolitesView.as_view()),
    path('genome_detail_signal_peptides', genomes_views.BacteriaGenomeSignalPeptidesView.as_view()),
    path('genome_detail_signal_peptides_unmag', genomes_views.UnMAGBacteriaGenomeSignalPeptidesView.as_view()),
    path('genome_detail_virulence_factors', genomes_views.BacteriaGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_virulence_factors_unmag', genomes_views.UnMAGBacteriaGenomeVirulenceFactorsView.as_view()),
    path('genome_detail_antibiotic_resistance', genomes_views.BacteriaGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_antibiotic_resistance_unmag',
         genomes_views.UnMAGBacteriaGenomeAntibioticResistanceGenesView.as_view()),
    path('genome_detail_transmembrane_helices', genomes_views.BacteriaGenomeTransmembraneHelicesView.as_view()),
    path('genome_detail_transmembrane_helices_unmag',
         genomes_views.UnMAGBacteriaGenomeTransmembraneHelicesView.as_view()
         ),
    path('genome_fasta', genomes_views.BacteriaGenomeFASTAView.as_view()),
    path('genome_fasta_unmag', genomes_views.UnMAGBacteriaGenomeFASTAView.as_view()),
]
