# Generated by Django 4.2 on 2025-05-20 06:08

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fungi_database", "0002_remove_magfungi_fungi_id_gca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magfungisecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagfungisecondarymetaboliteregion",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magfungisecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="mf_sm_type_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagfungisecondarymetaboliteregion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["type"], name="umf_sm_type_gin_idx"
            ),
        ),
    ]
