# Generated by Django 4.2 on 2025-06-22 16:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fungi_database", "0005_alter_magfungi_contig_n50_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magfungi",
            name="fungi_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="magfungi",
            name="organism_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magfungi",
            name="species",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="magfungiprotein",
            name="cog_category",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagfungi",
            name="fungi_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="unmagfungi",
            name="organism_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagfungi",
            name="species",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="unmagfungiprotein",
            name="cog_category",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="magfungi",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["fungi_id"], name="mf_fungi_id_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="magfungiprotein",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cog_category"], name="mf_cog_category_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagfungi",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["fungi_id"], name="umf_fungi_id_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unmagfungiprotein",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cog_category"], name="umf_cog_category_gin_idx"
            ),
        ),
    ]
