# Generated by Django 5.2.3 on 2025-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fungi_database",
            "0006_alter_magfungi_fungi_id_alter_magfungi_organism_name_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="cs_probability",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="lipo_sec_spii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="pilin_sec_spiii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="sp_sec_spi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="tat_tat_spi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magfungisignalpeptideprediction",
            name="tatlipo_tat_spii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="cs_probability",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="lipo_sec_spii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="pilin_sec_spiii",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="sp_sec_spi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="tat_tat_spi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unmagfungisignalpeptideprediction",
            name="tatlipo_tat_spii",
            field=models.TextField(blank=True, null=True),
        ),
    ]
